name: device_definition_converter
description: "Utility package to convert to OXI device definition"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  csv: ^6.0.0

executables:
  convert_midi_guide_instruments:

